set $mod Mod4
set $i3configdir ~/.config/i3
set $i3blockdir ~/.config/i3blocks
set $scriptsdir $i3configdir/scripts
floating_modifier $mod
tiling_drag modifier titlebar
set $ws1  "1:" 
set $ws2  "2:" 
set $ws3  "3:" 
set $ws4  "4:" 
set $ws5  "5:" 
set $ws6  "6"
set $ws7  "7"
set $ws8  "8:" 
set $ws9  "9:漣"
set $ws10 "10:"
