# ======================================================
# Autostart - Programas que se ejecutan al iniciar i3
# ======================================================
# Iniciar el demonio de GNOME Keyring para almacenar secretos (para gh, etc.)
exec --no-startup-id dbus-launch --exit-with-session gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
exec --no-startup-id numlockx on
exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork 
exec --no-startup-id nm-applet
exec --no-startup-id clipit
exec --no-startup-id sh -c "sleep 2 && volumeicon"
exec --no-startup-id picom -b
exec_always --no-startup-id nitrogen --restore
exec --no-startup-id gammastep-gtk
exec --no-startup-id exportXDG_MENU_PREFIX=plasma-
exec --no-startup-id /usr/bin/kbuildsycoca6 --noincremental






