# ======================================================
# Autostart - Programas que se ejecutan al iniciar i3
# ======================================================

# Activar NumLock al inicio (si lo deseas)
exec --no-startup-id i3-msg "set_input_mode numlock"

# Ejecutar archivos .desktop según estándar XDG (programas de inicio)
exec --no-startup-id dex --autostart --environment i3

# Bloqueo de pantalla automático antes de suspensión y con i3lock
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork # O tu comando i3lock preferido

# Applet de NetworkManager para administrar redes
exec --no-startup-id nm-applet

# Iniciar Clipit (gestor de portapapeles)
exec --no-startup-id clipit

# Opcional: Script de autostart para volumeicon (si no usas i3blocks para volumen)
#exec --no-startup-id $i3configdir/autostart_volumeicon.sh

# Compositor para transparencias y efectos
exec --no-startup-id picom -b

# Gestor de fondos de pantalla (Nitrogen)
exec_always --no-startup-id nitrogen --restore

# Para cuidado visual (temperatura de color)
exec --no-startup-id gammastep-gtk # O redshift-gtk

# Opcional: Iniciar una terminal en un workspace específico al arrancar i3
exec --no-startup-id i3-msg 'workspace number $ws1; exec i3-sensible-terminal'
