# ==============================================================================
# i3wm Keybindings (Atajos de Teclado Personalizados)
#
# Este archivo contiene atajos de teclado adicionales o personalizados
# que no encajan en las otras categorías.
# ==============================================================================

# --- Atajos de Teclado para Layouts de Teclado ---
bindsym $mod+Control+k exec "setxkbmap es && setxkbmap latam"


