# ======================================================
#         Configuración Visual de i3 y i3bar
# ======================================================

# --- Fuente Principal ---
# Define la fuente para las barras de título de las ventanas.
font pango:JetBrainsMono Nerd Font 11


# --- Configuración de la Barra (i3bar) ---
bar {
    # IMPORTANTE: Aquí apuntamos al nuevo script wrapper para centrar los bloques.
    status_command i3blocks

    position top
    font pango:JetBrainsMono Nerd Font 10

    # No mostrar los números "1:", "2:", etc., solo los nombres/iconos.
    strip_workspace_numbers yes
    workspace_buttons yes
    
    # Dónde mostrar la bandeja del sistema (nm-applet, clipit, etc.)
    tray_output primary 
    tray_padding 2

    # Colores de la barra
    colors {
        background #222222
        statusline #bbbbbb
        separator  #666666

        #                   borde   fondo   texto
        focused_workspace  #4c7899 #285577 #ffffff
        active_workspace   #333333 #5f676a #ffffff
        inactive_workspace #333333 #222222 #888888
        urgent_workspace   #2f343a #900000 #ffffff
        binding_mode       #2f343a #900000 #ffffff
    }
}


# --- Colores de las Ventanas ---
# Define los colores para los bordes y la barra de título de las ventanas.
# clase                 borde   fondo   texto   indicador  borde_hijo
client.focused          #4c7899 #285577 #ffffff #2e9ef4   #285577
client.focused_inactive #333333 #5f676a #ffffff #484e50   #5f676a
client.unfocused        #333333 #222222 #888888 #292d2e   #222222
client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c

client.background #ffffff


# --- Gaps y Bordes ---
# Espacios entre ventanas y con los bordes de la pantalla.
gaps inner 8
gaps outer 4

# Los Gaps solo se aplican si hay más de una ventana en el workspace.
smart_gaps on

# Los bordes de las ventanas solo se muestran si hay más de una.
smart_borders on

# Grosor del borde de las ventanas.
for_window [class="^.*"] border pixel 2