# ======================================================
# Reglas de Ventanas (Asignaciones y Comportamiento)
# ======================================================

# Asignar aplicaciones a workspaces específicos
# ---------------------------
assign [class="(?i)firefox"] $ws2
assign [class="(?i)google-chrome(-stable)?"] $ws2
assign [class="(?i)chromium"] $ws2
assign [class="(?i)vivaldi(-stable)?"] $ws2
assign [class="Code"] $ws3 # VSCode
assign [class="(?i)thunar"] $ws4
assign [class="Pcmanfm"] $ws4
assign [class="(?i)telegramdesktop"] $ws5
assign [class="(?i)discord"] $ws5
assign [class="Cmus"] $ws8
assign [class="(?i)pavucontrol"] $ws9
assign [class="(?i)lxappearance"] $ws9
assign [class="(?i)mpv"] $ws10
assign [class="(?i)vlc"] $ws10

# Reglas para ventanas específicas
# ---------------------------
for_window [class="(?i)galculator"] floating enable
for_window [class="(?i)nitrogen"] floating enable, sticky enable
for_window [class="Lxappearance"] floating enable
for_window [class="Pavucontrol"] floating enable
for_window [title="(?i)file operation progress"] floating enable
for_window [title="(?i)preferencias"] floating enable # Para diálogos de preferencias
for_window [window_role="(?i)pop-up"] floating enable
for_window [window_role="(?i)bubble"] floating enable
for_window [window_role="(?i)dialog"] floating enable
for_window [window_type="(?i)dialog"] floating enable
for_window [window_type="(?i)splash"] floating enable, sticky enable
