
assign [class="(?i)google-chrome(-stable)?"] $ws2
assign [class="Code"] $ws3
assign [class="Pcmanfm"] $ws4
assign [class="(?i)telegramdesktop"] $ws5
assign [class="(?i)discord"] $ws6
assign [class="Cmus"] $ws8
assign [class="(?i)pavucontrol"] $ws9
assign [class="(?i)lxappearance"] $ws9
assign [class="(?i)mpv"] $ws10
assign [class="(?i)vlc"] $ws10

for_window [class="(?i)galculator"] floating enable
for_window [class="(?i)nitrogen"] floating enable, sticky enable
for_window [class="Lxappearance"] floating enable
for_window [class="Pavucontrol"] floating enable
for_window [title="(?i)file operation progress"] floating enable
for_window [title="(?i)preferencias"] floating enable
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="dialog"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_type="splash"] floating enable, sticky enable
