# Variables para Waybar y Scripts (Ajustadas a herramientas instaladas)
set $term foot
set $term_float foot --title="floating_shell"
set $menu wofi --show drun
set $calendar foot -e calcurse || foot -e cal
set $task_manager foot -e btop
set $pulseaudio foot -e pulsemixer
set $volume_mute wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
set $volume_up wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
set $volume_down wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
set $brightness_up brightnessctl set +5%
set $brightness_down brightnessctl set 5%-
set $clipboard cliphist list | wofi --dmenu | cliphist decode | wl-copy
set $clipboard-del cliphist list | wofi --dmenu | cliphist delete
set $update_manager pamac-manager
set $bluetooth foot -e bluetoothctl
set $once --no-startup-id

# Theme environment variables
exec systemctl --user set-environment QT_QPA_PLATFORMTHEME=qt6ct
exec_always dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP


