# ==========================================
# Atajos del Sistema y Navegación Sway
# ==========================================
bindsym $mod+i exec ~/.local/bin/sway-next-workspace-browser.sh
bindsym $mod+g exec ~/.local/bin/sway-next-workspace-agy.sh
