# ==============================================================================
# Manjaro Sway Special Modes (Power & Screenshots)
# ==============================================================================

# --- Power Menu Mode ---
set $mode_system (l)ock, (e)xit, (s)uspend, (r)eboot, (P)oweroff
mode "$mode_system" {
    bindsym l exec $locking, mode "default"
    bindsym e exec swaymsg exit
    bindsym s exec systemctl suspend, mode "default"
    bindsym r exec systemctl reboot
    bindsym p exec systemctl poweroff
    
    # Return to default mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
unbindsym $mod+Shift+e
bindsym $mod+Shift+e mode "$mode_system"

# --- Screenshot Mode ---
set $mode_screenshot (p)ick, (o)utput
mode "$mode_screenshot" {
    # Output = currently active output
    bindsym o mode "default", exec grim ~/Imágenes/$(date +%Y-%m-%d-%H%M%S).png && notify-send "Pantalla completa guardada"
    
    # Pick = selection
    bindsym p mode "default", exec grim -g "$(slurp)" ~/Imágenes/$(date +%Y-%m-%d-%H%M%S).png && notify-send "Selección guardada"

    # Return to default mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
# unbindsym Print
# bindsym Print mode "$mode_screenshot"
